name: Git Sync Action
on: push
jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
    - name: ssh
      uses: webfactory/ssh-agent@v0.2.0
      with:
        ssh-private-key: ${{ secrets.BITBUCKET_SECRET }}
        ssh_private_key: ${{ secrets.BITBUCKET_SECRET }}

    - name: repo-sync
      uses: wei/git-sync@v2
      with:
        source_repo: "https://github.com/GameServerManagers/LinuxGSM"
        source_branch: "master"
        destination_repo: "https://dgibbs64@bitbucket.org/dgibbs64/linuxgsm"
        destination_branch: "master"
        ssh_private_key: ${{ secrets.BITBUCKET_SECRET }}
        
        
